name: Build Hangar

on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '20'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Publish
        uses: benwoo1110/hangar-upload-action@v1
        with:
          api_token: ${{ secrets.HANGAR_TOKEN }}
          slug: 'OliiksLoginMsgs'
          version: ${{ github.event.release.tag_name }}
          channel: release
          files: |
            [
              {
                "path": "target/oliiksloginmsgs-*-shaded.jar",
                "platforms": ["PAPER"]
              }
            ]