name: Java CI with Maven

on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '20'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Release
      uses: HSGamer/action-mcreleaser@main
      with:
        files: /home/runner/work/OliiksLoginMsgs/OliiksLoginMsgs/D:/OliiksLoginMsgs/run/plugins/oliiksloginmsgs-1.3.jar
      env:
        NAME: 1.3
        DESCRIPTION: Added commands for changing the messages
        GAME_VERSIONS: ("1.19.4" "1.21.4")
        VERSION: "1.3"

        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        GITHUB_REPOSITORY: OliiksLoginMsgs
        GITHUB_REF: 3b395e7

        HANGAR_KEY: ${{ secrets.HANGAR_KEY }}
        HANGAR_PROJECT: OliiksLoginMsgs
        HANGAR_CHANNEL: Release
        HANGAR_PLATFORM: paper
        HANGAR_GAME_VERSIONS: ("1.19.4" "1.21.4")

